### ISSUE TITLE
Podspecs Broken?

### ISSUE THREAD

**Issue by norsez** [brunow/BaseKit#10]
Today when I do a 'pod install' on one of my projects with BaseKit as a dependency, BaseKit gets omitted from the install. This did not happen last week though. I am not really sure what happens. I have tried it with a brand new project. Same problem. Any advice please?

Thanks, 

Norsez

**Comment by brunow** [comment]
Which version do you use ?
I just created a test project with

```
dependency 'BaseKit/CellMapping', '~> 0.2.3'
dependency 'BaseKit/LocationManager', '~> 0.2.3'
```

And it seems to work, I have in the Pods/BaseKit/Code/ all dependency that I must have

Can you check if you have BaseKit files into these directory ?

**Comment by norsez** [comment]
This one is my bad. I only had 

dependecny 'BaseKit' 

in the Podfile thinking it would install everything. I have just tested it the way you wrote above and it worked fine. Sorry and thank you for coming back on the question so quickly.

n

**Comment by brunow** [comment]
Ok good if it work now
