### ISSUE TITLE
BKLocationManager memory leak on Line 54?

### ISSUE THREAD

**Issue by VeeruPV** [brunow/BaseKit#11]
Hi there
The LocationManager with blocks work beautifully, but when i analyze the app, it shows there might be a potential leak in line 54 of BKLocationManager.m

return [[self alloc] init];

I wonder if this is a false error, or is it safe to change it to [[[self alloc] init]autorelease]

Thanks

**Comment by brunow** [comment]
Hi,

It's not said on readme but master branch is now ARC only, so don't add autorelease. The last version that support ARC and non-ARC will be the 0.2.x. Master is also a development branch if you need stable release please use stable branch.

**Comment by VeeruPV** [comment]
Thanks brunow,

Am just using the loctionmanager from basekit, nothing else. And my project is non-ARC. How can i just add ARC to locatoinmanager only? Is it just adding -fobj-arc to BKLocationManager.m? 

When i did that, analyze doe'snt show any more potential leaks. Am i safe?

**Comment by brunow** [comment]
Yes with the flag you've added you're good, no memory leaks.

**Comment by VeeruPV** [comment]
Great thanks, that takes one burden off my mind - am just about to submit my app :)
