### ISSUE TITLE
replace accessory image at onSelectRowWithBlock NOT working

### ISSUE THREAD

**Issue by angeloh** [brunow/BaseKit#13]
The new image is not replaced when row is selected. The following block has been executed as expected.   

[cellMapping onSelectRowWithBlock:^(UITableViewCell _cell, Item *item, NSIndexPath *indexPath) {
           UIImageView_ accessoryView = (UIImageView *)cell.accessoryView;
            UIImage *newImage = [UIImage imageNamed:@"Images/unchecked.png"];
            [accessoryView setImage:newImage];
 }];

**Comment by angeloh** [comment]
Ok. I found the solution. I have to use UIButton and add a tap selector using willDisplayCellWithBlock. However, I have to fix one bug at BKTableModel to make it work.

At custom cell,

```
    UIButton _cellAccessoryBtn = [UIButton buttonWithType:UIButtonTypeCustom];
    [_cellAccessoryBtn setShowsTouchWhenHighlighted:YES];
    _cellAccessoryBtn.frame = frame;    // match the button's size with the image size
    [_cellAccessoryBtn setBackgroundImage:image forState:UIControlStateNormal];
    [self setAccessoryView:_cellAccessoryBtn];
```

At Controller,

```
     [cellMapping willDisplayCellWithBlock:^(UITableViewCell *cell, id object, NSIndexPath *indexPath) {
            UIButton* accessoryBtn = (UIButton *)cell.accessoryView;
            [accessoryBtn addTarget:self action:@selector(checkButtonTapped:event:) forControlEvents:UIControlEventTouchUpInside];
     }];
```

Then when I tap the accessory button, the image can be changed in the selector.

However, there is on Bug at BKTableModel that needs to be fixed to make it work.

```
     - (void)willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath {
         id object = [self objectForRowAtIndexPath:indexPath];
         BKCellMapping *cellMapping = [self cellMappingForObject:object];

         if (nil != cellMapping.willDisplayCellBlock) {
     //        UITableViewCell *cell = [self cellForRowAtIndexPath:indexPath];
             cellMapping.willDisplayCellBlock(cell, object, indexPath);
         }
     }
```

**Comment by brunow** [comment]
That's right thanks you @angelokh for your report !

**Comment by brunow** [comment]
It's fixed in stable and master branch.
