### ISSUE TITLE
titleForHeaderInSection for BKManagedTableModel

### ISSUE THREAD

**Issue by angeloh** [brunow/BaseKit#14]
This is missing from BKManagedTableModel.
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
  int count = [self numberOfSections];
  if (count > section) {
      id <NSFetchedResultsSectionInfo> sectionInfo = [[self.fetchedResultsController sections] objectAtIndex:section];
      return [sectionInfo name];
  }
  return nil;
  }

**Comment by brunow** [comment]
BaseKit cell mapping doesn't handle section so I'll not add this to BKManagedTableModel. But you can easily extend BKManagedTableModel to add stuff.

**Comment by angeloh** [comment]
Do you mean BKManagedTableModel can not be used for sections? I tried it and it worked for me. Do I miss anything?

**Comment by brunow** [comment]
No you've right that will work, sorry for that. I thought a title would be displayed even when you do not want. But if you don"t group data title will not be displayed.

I've not announced that yet on the readme but cell mapping will be removed soon from BaseKit. I've created a new projet called TableKit https://github.com/brunow/TableKit.m. It has the same functionality as master branch has.

I'll add your fix soon into TableKit.m

Thank you !
