### ISSUE TITLE
reloadRowsAtIndexPaths when NSFetchedResultsChangeUpdate

### ISSUE THREAD

**Issue by angeloh** [brunow/BaseKit#15]
please add reloadRowsAtIndexPaths to below case:
- (void)controller:(NSFetchedResultsController *)controller
  didChangeObject:(id)anObject
     atIndexPath:(NSIndexPath *)indexPath
   forChangeType:(NSFetchedResultsChangeType)type
    newIndexPath:(NSIndexPath *)newIndexPath {
  
  UITableView *tableView = self.tableView;
  
  switch(type) {
      case NSFetchedResultsChangeUpdate:
          [self cellForRowAtIndexPath:indexPath];
          [tableView reloadRowsAtIndexPaths:[tableView indexPathsForVisibleRows] 
                           withRowAnimation:UITableViewRowAnimationNone];
          break;
  }
  }

**Comment by brunow** [comment]
Fixed thank you
