### ISSUE TITLE
A conflict between BaseKit and BlocksKit

### ISSUE THREAD

**Issue by lexrus** [brunow/BaseKit#5]
Hi, @brunow and @zwaldowski
Both repo has a macro file named BKMacros.h, so there will be a build time error when I include them in my project. Is there any config trigger to avoid it?

**Comment by zwaldowski** [comment]
I could take the little kid's way out and say BlocksKit was here first. ;-) But the BKMacros file (as far as BlocksKit) has absolutely no effect on the rest of the codebase and can be deleted freely.

**Comment by brunow** [comment]
Hi,

I use too BlocksKit and BaseKit on some project, but I haven't note this problem because I didn't update BaseKit on last version.
So I think the easiest way would be to change the file name, as @zwaldowski  said before he's the first one so I'll change my file name.

**Comment by brunow** [comment]
I juste renamed the file BKMacrosDefinitions.h
