### ISSUE TITLE
How to use BKTableModel in UIViewController?

### ISSUE THREAD

**Issue by steve21124** [brunow/BaseKit#9]
Currently, BKTableModel use UITableViewController instead of UIViewController. I create table automatically using UITableView.

**Comment by brunow** [comment]
It's very simple here is a simple example:

``` objectivec
UITableView *myTableView = [[UITableView alloc] initWithFrame:CGRectZero];
BKTableModel *model = [BKTableModel tableModelForTableView:myTableView];
```

Just provide your tableview instance when you instantiate your tablemodel

**Comment by steve21124** [comment]
It give error "CellMappingExample[16650:207] -[BKTableModel superview]: unrecognized selector sent to instance 0x6a2caf0"

   // self.tableView= [[UITableView alloc] initWithFrame:CGRectZero];
    self.tableView= [[UITableView alloc] initWithFrame:self.view.bounds];
  //  self.tableView = [BKTableModel tableModelForTableView:self.tableView delegate:self];
    [self.view addSubview:self.tableView];

----------- This below create UITableView fine
@interface TableViewControllerExample : UIViewController<BKTableModelDataSource,UITableViewDataSource,UITableViewDelegate>{

}
- (void)viewDidLoad {
  //  self.tableView= [[UITableView alloc] initWithFrame:CGRectZero]; 
  
    self.tableView= [[UITableView alloc] initWithFrame:self.view.bounds];
  
  //  self.tableView = [BKTableModel tableModelForTableView:self.tableView delegate:self];
  
    [self.view addSubview:self.tableView];
  }

**Comment by brunow** [comment]
You must not do that, BKTableModel don't hinerit from UITableView
self.tableView = [BKTableModel tableModelForTableView:self.tableView delegate:self];

Instead do some like
self.tableModel = [BKTableModel tableModelForTableView:self.tableView delegate:self];
were tableModel is a property of type BKTableModel

**Comment by steve21124** [comment]
thanks
